FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o health-service ./cmd/health-service/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/health-service .
CMD ["./health-service"]
